### PR TITLE
Implement DoubleEndedIterator for children

### PR DESCRIPTION
**Pull request by pbor**
Remove the ReverseChildren iterator and implement a double
ended iterator instead.

### CODE REVIEW

**Comment by RazrFalcon** [comment]
Thanks. What about `reverse_traverse`?

**Comment by pbor** [comment]
I am trying to replace a custom tree implementation with rctree and we have a double ended iterator... I could have just replaced our calls to children().rev() with reverse_children(), but I thought it might make sense to propose the double ended iterator upstream.

**Comment by pbor** [comment]
I can (try to) do reverse_traverse as well if you like the idea

**Comment by RazrFalcon** [comment]
Yes. I like it, because it's more idiomatic.

**Comment by pbor** [comment]
Cool, I will take a look at reverse_traverse then.

And thanks for the quick feedback.... this must be a record :smile:

**Comment by RazrFalcon** [comment]
Thanks!

I've missed your last patch for some reason.

**Pull request merged**
